### ISSUE TITLE
Image missing for the deployment of rancher after updating version

### ISSUE THREAD

**Issue by MozeBaltyk** [clemenko/rke_airgap_install#10]
Hello Clemenko

Since update on rancher version to 2.8.0, it need some mirrored image:
```
manager  ●  localhost:5000/rancher/mirrored-cluster-api-controller:v1.4.4  false  ImagePullBackOff 
``` 

which is missing in the zst package due to exclusion from the list: 
```sh
# remove things that are not needed and overlapped
  sed -i -E '/neuvector|minio|gke|aks|eks|sriov|harvester|mirrored|longhorn|thanos|tekton|istio|hyper|jenkins|windows/d' rancher/orig_rancher-images.txt
```

for this one :
```
 patch-sa-cattle-provisioning-capi-system  ●  localhost:5000/rancher/kubectl:v1.20.2  false  ImagePullBackOff
```

I think is excluded with the sorting and keeping only the latest

regards,

**Comment by clemenko** [comment]
There currently is an issue with upstream v2.8.0. Once it is fixed I will retest and fix the script.

**Comment by clemenko** [comment]
v2.8.1 came out. I am going to test today.

**Comment by clemenko** [comment]
Take a look at line 95 and 96.

**Comment by MozeBaltyk** [comment]
I did something similar in my code:

```yaml
- name: Rancher List - Due to version 2.8.0
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      echo "rancher/mirrored-cluster-api-controller:v1.4.4" >> {{ directory_package }}/images/rancher/images.txt
      echo "rancher/kubectl:v1.20.2" >> {{ directory_package }}/images/rancher/images.txt
    executable: /bin/bash
  changed_when: false
```

Now I am working with "renovate" to autoupdate rke2 and all dependencies. Then, I will work on CI and test. 

I did not had time to test the new rancher version but seems that 2.8.0 is to avoid and new to jump immediatly to 2.8.1
 
So did you had opportunity to test the RKub collection ?

By the way, where did you got the registry image ? is it a custom image or you got it from some registry ? I would like to put it in my `renovate.json` as well ...

**Comment by clemenko** [comment]
that is the upstream registry. I was pulling it then updating. I just fixed/updated the code to pull directly from docker hub.

**Comment by dmeiselman** [comment]
tested yesterday on Rocky 8.9, still seeing helm deployment get stuck on capi-controller-manager failing to pull mirrored-cluster-api-controller:v1.4.4 image. 

Oh also: you're still telling workers to install selinux-0.16 not 0.17. Might be worth declaring a $SELINUX_VERSION

**Comment by clemenko** [comment]
I'll take a look in the morning.

**Comment by dmeiselman** [comment]
we add cluster-api-controller to the list of images in cleaned_orig_rancher-images.txt, but not into rancher-images.txt. The skopeo operation at line 126 uses rancher-images.txt

**Comment by clemenko** [comment]
got it sorted. Also for el8! Check the latest.

**Comment by clemenko** [comment]
confirmed working with several people. feel free to reopen if it is still an issue.
